apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yeaktonghan-devops-simple-spring
spec:
  destination:
    name: ''
    namespace: yeaktonghan
    server: 'https://kubernetes.default.svc'
  source:
    path: app
    repoURL: 'https://github.com/KSGA-Autopilot/yeaktonghan-devops-simple-spring-cd-static-test'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
project: default
source:
  repoURL: 'https://github.com/KSGA-Autopilot/yeaktonghan-devops-simple-spring-cd-static-test'
  path: app
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: yeaktonghan
syncPolicy:
  automated:
    prune: true
    selfHeal: true
